repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: end-of-file-fixer
        files:
          glob:
            - "**/*"
            - "!**/flake.lock"
  - repo: local
    hooks:
      - id: nix-flake-check
        name: nix-flake-check
        entry: nix flake check
        language: system
        files: \.nix$
        pass_filenames: false
      - id: nix-fmt
        name: nix-fmt
        entry: treefmt
        language: system
        files: \.nix$
